commit1
abhijithbe/Training pull request #1
Opened 2022-09-07 03:51 UTC by abhijithbe

Bubble sort code developed in java in intellij.

2022-09-07 04:00 UTC, PrashanthRangarajan requested changes

2022-09-07 04:00 UTC, PrashanthRangarajan commented on bubblesort/src/bubblesort.java
> +public class bubblesort {
Please use PascalCase for classnames

2022-09-07 04:00 UTC, PrashanthRangarajan commented on bubblesort/src/bubblesort.java
> +    void bubble(int arr[]){
Please use camelCase for function names. This function has a single word so it's alright.
Also please add java-docs for all the functions and the class.

2022-09-07 04:00 UTC, PrashanthRangarajan commented on bubblesort/src/bubblesort.java
> +        for(int i=0;i<len-1;i++){
Prefer using java streams for iterating over an array of elements instead of traditional for loops.

2022-09-07 04:00 UTC, PrashanthRangarajan commented on bubblesort/src/bubblesort.java
> +        for(int i=0;i<arr.length;i++){
Please use java streams

2022-09-07 04:00 UTC, PrashanthRangarajan commented on bubblesort/src/bubblesort.java
> +    public static void main(String args[]){
It's a best practice to have space in between 2 functions.

2022-09-07 04:00 UTC, PrashanthRangarajan commented on bubblesort/src/bubblesort.java
> +        bubblesort b=new bubblesort();
Once you change the class name to PascalCase, this object name/constructor should also change. Also please come up with more descriptive names for the object instances(variables). The idea is to make your team-mates/reviewers understand the code just by looking at the names

2022-09-07 04:00 UTC, PrashanthRangarajan commented on bubblesort/src/bubblesort.java
> +        b.bubble(arr);
Please rename `arr` in a more readable way

2022-09-07 05:55 UTC, abhijithbe commented on bubblesort/src/bubblesort.java
> +public class bubblesort {
> Please use PascalCase for classnames

done

2022-09-07 05:55 UTC, abhijithbe commented on bubblesort/src/bubblesort.java
> +    void bubble(int arr[]){
done

2022-09-07 06:01 UTC, abhijithbe commented on bubblesort/src/bubblesort.java
> +        b.bubble(arr);
done

2022-09-07 06:01 UTC, abhijithbe commented on bubblesort/src/bubblesort.java
> +        bubblesort b=new bubblesort();
done

2022-09-07 06:01 UTC, abhijithbe commented on bubblesort/src/bubblesort.java
> +    public static void main(String args[]){
done

2022-09-08 04:22 UTC, PrashanthRangarajan requested changes

2022-09-08 04:22 UTC, PrashanthRangarajan commented on bubblesort/src/BubbleSort.java
> +public class BubbleSort {
Please add javadocs to the classes and functions

2022-09-08 04:22 UTC, PrashanthRangarajan commented on bubblesort/src/BubbleSort.java
> +        IntStream.range(0, array.length - 1).forEach(i ->
Extract the logic out of main function and put it in a function of it's own in the `BubbleSort` class

2022-09-08 04:22 UTC, PrashanthRangarajan commented on bubblesort/src/BubbleSort.java
> +        BubbleSort sorting_object = new BubbleSort();
Use camelCase instead of snake_case

2022-09-08 04:22 UTC, PrashanthRangarajan commented on bubblesort/src/BubbleSort.java
> +    public static int array[] = {6, 2, 3, 5, 1};
Pass this array from the main class

2022-09-08 04:55 UTC, closed without merging