Maven Changes
abhijithbe/Training pull request #5
Opened 2022-09-12 06:40 UTC by abhijithbe

2022-09-13 03:45 UTC, PrashanthRangarajan requested changes

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/pom.xml
> +
Please remove unnecessary extra spaces

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +public class GetTimeline {
Please add java doc for the class. Add yourself as author using `@author` annotation of javadoc

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +        TwitterFactory tf = new TwitterFactory(cb.build());
Better rename `tf` -> `twitterFactory`. Be liberal with naming. There's no harm in going as verbose as possible.

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +        }catch(Exception e){
Instead of catching a generic exception, find what exception is being thrown by the `getHomeTimeLine()` method and catch that exact exception over here.

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +        try{
Please maintain a general rule that there should be a space before and after curly braces at all the places.

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/Main.java
> +public class Main {
Rename `Main` -> `SimpleTwitterApp` or something else to exactly describe what your app does.

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/Main.java
> +        while(flag){
Your main function should never perform any logical operation. It should only be the caller of all other functions. Please extract out this logical steps and create a new method in this class. Call that method over here.

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/Main.java
> +        Scanner sc=new Scanner(System.in);
Rename `sc` -> `scanner`

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/Main.java
> +                    String tweetMessage=sc.next();
As mentioned for curly braces, it's best practice to have spaces before and after `=` too. These things make the code much more readable

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/PostTweet.java
> +public class PostTweet {
Please add javadoc for the class

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/PostTweet.java
> +        }catch (Exception e){
Please catch the exact function thrown by `getInstance` method.

2022-09-13 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +     * The getTimeline function basically authenticates the user using keys
Good elaborate documentation 👍

2022-09-13 03:52 UTC, PrashanthRangarajan requested changes

2022-09-13 03:52 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +public class GetTimeline {
Generally the name of a class should be a noun and the method name should be a verb. You can rename this class to `Timeline` or `TwitterTimeLine` and can call `twitterTimeLine.getTimeline()` when you wanna render the timeline

2022-09-13 06:37 UTC, abhijithbe commented on MavenProject/pom.xml
> +
Done

2022-09-13 06:38 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +public class GetTimeline {
Added

2022-09-13 06:39 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +        TwitterFactory tf = new TwitterFactory(cb.build());
changed

2022-09-13 06:40 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +        }catch(Exception e){
done

2022-09-13 06:40 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +        try{
done

2022-09-13 06:40 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/Main.java
> +        Scanner sc=new Scanner(System.in);
changed

2022-09-13 06:40 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/PostTweet.java
> +public class PostTweet {
done

2022-09-13 06:41 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/PostTweet.java
> +        }catch (Exception e){
done

2022-09-13 06:46 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +public class GetTimeline {
changed

2022-09-13 06:46 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/GetTimeline.java
> +     * The getTimeline function basically authenticates the user using keys
okay

2022-09-13 06:46 UTC, abhijithbe commented on MavenProject/src/main/java/org/example/Main.java
> +                    String tweetMessage=sc.next();
changed

2022-09-15 03:45 UTC, PrashanthRangarajan approved these changes

2022-09-15 03:45 UTC, PrashanthRangarajan commented on MavenProject/src/main/java/org/example/SimpleTwitterApp.java
> +     * performes the operations based on user choice
typo

2022-09-15 03:56 UTC, merged